### ISSUE TITLE
How do i stop the logger.

### ISSUE THREAD

**Issue by jamesjohnson1025** [seratch/notion-sdk-jvm#125]
Is the the logger configurable. I don't want to output crawled data to stdout. Currently every crawled data is logged in stdout.

**Comment by seratch** [comment]
Hi @jamesjohnson1025, I'd suggest switching to a 3rd-party logging library for better control of outputs: https://github.com/seratch/notion-sdk-jvm#pluggable-logging My primary recommendation is logback library. You can place a configuration file under src/main/resources (e.g., logback.xml) to set logging level and how to write logs.
