### ISSUE TITLE
Android - Unresolved reference: NotionClient

### ISSUE THREAD

**Issue by pigking12345** [seratch/notion-sdk-jvm#26]
I am trying to import the library to an Android project, but the compiler complains "Unresolved reference: NotionClient".

Kotlin version 1.5.30.
Dependencies: com.github.seratch:notion-sdk-jvm-core:0.1.16

Source code:
```
import notion.api.v1.NotionClient
import notion.api.v1.model.pages.PageParent
import notion.api.v1.model.pages.PageProperty as prop

class NotionApi {
}
```

Is Android supported?

**Comment by seratch** [comment]
Yes, it is. I've verified if it works before. Perhaps, the part of adding dependencies in your build settings should have some issues.

**Comment by seratch** [comment]
Let me close this issue due to inactivity. I don't think that this is an issue on this SDK side but if someone else faced the same issue, please feel free to write in.
