### ISSUE TITLE
Unable to make field private final sun.net.www.protocol.https.DelegateHttpsURLConnection

### ISSUE THREAD

**Issue by paullarionov** [seratch/notion-sdk-jvm#28]
During update page via client.updatePageProperties I get error:

`Unable to make field private final sun.net.www.protocol.https.DelegateHttpsURLConnection sun.net.www.protocol.https.HttpsURLConnectionImpl.delegate accessible: module java.base does not "opens sun.net.www.protocol.https" to unnamed module @2752f6e2`

Please tell how to fix it.

**Comment by denisosteo** [comment]
Could you provide syntax to swith HTTP Client to define in Maven and for setHTTPClient in java?

**Comment by scordio** [comment]
@denisosteo here's what I use in a Java 17 project:

```xml
<dependency>
  <groupId>com.github.seratch</groupId>
  <artifactId>notion-sdk-jvm-core</artifactId>
  <version>${notion-sdk-jvm.version}</version>
</dependency>
<dependency>
  <groupId>com.github.seratch</groupId>
  <artifactId>notion-sdk-jvm-httpclient</artifactId>
  <version>${notion-sdk-jvm.version}</version>
</dependency>
<dependency>
  <groupId>com.github.seratch</groupId>
  <artifactId>notion-sdk-jvm-slf4j2</artifactId>
  <version>${notion-sdk-jvm.version}</version>
</dependency>
```

```java
var client = new NotionClient(token);
client.setHttpClient(new JavaNetHttpClient());
client.setLogger(new Slf4jLogger());
```

**Comment by denisosteo** [comment]
Thanks a lot, worked fine
