### ISSUE TITLE
How to retrieve value when property is rollup?

### ISSUE THREAD

**Issue by enrico-laboratory** [seratch/notion-sdk-jvm#30]
First of all thanks for creating this client, helping me a lot.

I would need to retrieve the value of some rollup properties, but not sure how to do it.

This is how I am accessing value for other properties type:
`List<Page> database = client.queryDatabase(new QueryDatabaseRequest(DatabaseList.REPERTOIRE_DATABASE)).getResults();
String title = database.get(0).getProperties().get("Order").getTitle().get(0).getPlainText()`

I don't seem to find a way to access to the rollup values using the same path:
`Rollup musicRollup = database.get(0).getProperties().get("Music Rollup").getRollup()`

The Rollup class contains only the 3 key related to the rollup itself but not the content of the rollup.

Is there another way I should access the rollup values?

Thank you for your help!

**Comment by seratch** [comment]
Honestly, I'm not an active Notion user and don't know about rollup properties very well. If this SDK needs to be updated to support your use case, I'm happy to enhance the code. 

When you have a feature request, sharing the JSON data you receive from the Notion server-side with me would be helpful. You can easily get the data by enabling debug-level logging.

**Comment by enrico-laboratory** [comment]
Thank you for your answer.

The rollup field will query a field in another table which the original table is related to.

This is a JSON answer you get for a rollup field with `"function"="show_original"`

`        "rollup": {
            "type": "array",
            "array": [
              {
                "type": "title",
                "title": [
                  {
                    "type": "text",
                    "text": {
                      "content": "Gamba intermezzo",
                      "link": null
                    },
                    "annotations": {
                      "bold": false,
                      "italic": false,
                      "strikethrough": false,
                      "underline": false,
                      "code": false,
                      "color": "default"
                    },
                    "plain_text": "Gamba intermezzo",
                    "href": null
                  }
                ]
              }
            ],
            "function": "show_original"`

This is the Rollup object:
`Rollup musicRollup = database.get(0).getProperties().get("Music Rollup").getRollup()`

`Rollup(type=array, number=null, function=show_original)`

What it is missing in the Java object is the key `array` which contains the values the rollup field is referring to and it would be great if it can be accessed via:
`Rollup musicRollup = database.get(0).getProperties().get("Music Rollup").getRollup().getArray().get(i).getTitle().get(0).getPlainText()`

Hope it does make sense. Thanks!

**Comment by seratch** [comment]
@enrico-laboratory Thanks for sharing the JSON data! #31 resolves this issue and I will release a new version shortly

**Comment by seratch** [comment]
Hey @enrico-laboratory, 0.1.19 is released. thanks again for your input!

**Comment by enrico-laboratory** [comment]
Thank you a lot!
