### ISSUE TITLE
Is it possible to filter a query?

### ISSUE THREAD

**Issue by enrico-laboratory** [seratch/notion-sdk-jvm#33]
Hi! I Is there a way to apply filter to a query? 

I am requesting a quite big database and I am not getting back all the records present in the db, response code 200. I am not sure there is a limit to the size of the json. I have tried with another client and I am getting the same issue.

I just need few records from that database, maybe with a filter I can solve the problem.

On QueryDatabaseRequest I see there is a constructor with filter and sorting in the signature, not sure how to use them or if it has been implemented at all.

Thank you for your help.

**Comment by seratch** [comment]
Hey @enrico-laboratory, checking the following code examples and documents would be helpful to you!

* https://github.com/seratch/notion-sdk-jvm/blob/v0.2.0/core/src/test/kotlin/integration_tests/DatabasesTest.kt#L131-L155
* https://developers.notion.com/reference/post-database-query#compound-filters

For general questions about the Notion platform, you can ask their developer community too: https://notiondevs.slack.com/join/shared_invite/zt-vkinpzs0-hJSEAAxJzPMuiCNvZETF2A#/shared-invite/email

**Comment by enrico-laboratory** [comment]
Indeed what I was looking for. Thank you!
(I should have checked the tests myself)

Thank you again for your great work!
