### ISSUE TITLE
ImageBlock does not contain uploaded file link

### ISSUE THREAD

**Issue by EsQLap** [seratch/notion-sdk-jvm#35]
Hello, I found that the ImageBlock does not get links like this. This link is created when you upload an image to the Notion. Is it planned to add getting this link?
![image](https://user-images.githubusercontent.com/61599652/153759994-79ff5e67-3556-4063-a4bf-93f242edbd06.png)

**Comment by seratch** [comment]
Hi @EsQLap, thanks for taking the time to report this. I was a bit confused with [the document](https://developers.notion.com/reference/block#image-blocks) 😅  but indeed, it seems that "file" type image element should be supported too. I will fix this in the next release!

**Comment by seratch** [comment]
v0.4.2 should have the property!
