### ISSUE TITLE
Is it possible to create nested compound filter?

### ISSUE THREAD

**Issue by enrico-laboratory** [seratch/notion-sdk-jvm#38]
Hi! 

Is it possible to create nested compound filters for QueryDatabase?

Example:
```
{
    "filter": {
        "or": [
            {
                "property": "Description",
                "rich_text": {
                    "contains": "fish"
                }
            },
            {
                "and": [
                    {
                        "property": "Food group",
                        "select": {
                            "equals": "🥦Vegetable"
                        }
                    },
                    {
                        "property": "Is protein rich?",
                        "checkbox": {
                            "equals": true
                        }
                    }
                ]
            }
        ]
    }
}
```
I checked this for CompoundFilter:
https://github.com/seratch/notion-sdk-jvm/blob/v0.2.0/core/src/test/kotlin/integration_tests/DatabasesTest.kt#L131-L155

I managed to use the Compound Filter but could not find a way to have the nested compound.

Thank you for your help!

**Comment by seratch** [comment]
Hi @enrico-laboratory, thanks for the feedback! We'll fix this issue in the next release - here is a PR fixing this issue: https://github.com/seratch/notion-sdk-jvm/pull/39

**Comment by seratch** [comment]
version 1.2.0 is out. The latest version should work for you. Thanks again for reporting this issue!

**Comment by enrico-laboratory** [comment]
Thank you!
