### ISSUE TITLE
updating cells /rows in simple tables

### ISSUE THREAD

**Issue by maplat1** [seratch/notion-sdk-jvm#42]
Hey, looks like block updates with table row elements arent working (or I'm doing it the wrong way) - any help much appreciated

**Comment by seratch** [comment]
Hey I'm not sure what your question is yet. Can you share a bit more details such as code and/or some examples using the official SDK?

**Comment by maplat1** [comment]
sure - I have a simple table (not a database table) on my page and want to update single cells 

I can perfectly read the content of the table via getBlocksChildren("blockid of table")

no trying to update each block returned (a TableRow)

`                client.updateBlock(
                    block.id!!,
                    mapOf(
                        BlockType.TableRow to BlockElementUpdate(cells)
                    )
                )
`

produces invalid JSON `Got an error from Notion (status: 400, code: validation_error, message: body failed validation: body.table_row.cells should be defined, instead was `undefined`.)`

hope that helps. As said not sure I'm doing something wrong but it feels like BlockElementUpdate data class only supports blocks with richText but does not have a "cells" property which would be needed here

thx for your help

**Comment by seratch** [comment]
Thanks for sharing the details! The operation is not yet supported in this SDK. I just submitted a pull request resolving this. https://github.com/seratch/notion-sdk-jvm/pull/43 

I will release a new version shortly

**Comment by seratch** [comment]
You can try v1.3.1

**Comment by maplat1** [comment]
thx for the fast turnaround! Working!
