### ISSUE TITLE
NotionClient constructor difficult to call from Java

### ISSUE THREAD

**Issue by heuermh** [seratch/notion-sdk-jvm#50]
It would be nice to call the `NotionClient` constructor from Java similar to the Kotlin example
```kotlin
val client = NotionClient(
    token = System.getenv("NOTION_TOKEN"),
    httpClient = JavaNetHttpClient(),
    logger = Slf4jLogger(),
)
```

It is not that straightforward however, and requires a magic `boolean` parameter to `GsonSerializer` constructor
```java
NotionClient client = new NotionClient(System.getenv("NOTION_TOKEN"),
                                       null,
                                       null,
                                       null,
                                       new JavaNetHttpClient(),
                                       new Slf4jLogger(),
                                       new GsonSerializer(false),
                                       "https://api.notion.com/v1");
```

Might it be possible to add a few Java-friendly constructors?  Thank you in advance.

**Comment by seratch** [comment]
I've submitted #51 for improving this. That being said, the keyword argument approach is not available in Java. Thus, I'd suggest using setter methods for some of the properties:

```java
NotionClient client = new NotionClient(System.getenv("NOTION_TOKEN"));
client.setHttpClient(new JavaNetHttpClient());
client.setLogger(new Slf4jLogger());
```

This is the recommended way to initialize your `NotionClient` instances in Java.
