### ISSUE TITLE
Captions on Images and Videos are not deserialized as Rich-Text

### ISSUE THREAD

**Issue by looorent** [seratch/notion-sdk-jvm#52]
### Problem encountered

When fetching Blocks including images and videos with captions, the caption seems to be parsed as a String and not a Rich-Text.
For a video, GSON produces:
```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected STRING but was BEGIN_OBJECT at path $.video.caption[0]
```
For an image, GSON produces:
```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected STRING but was BEGIN_OBJECT at path $.image.caption[0]
```

### How to reproduce

* Create a page including a video or an image
* Add a caption on this block
* Fetch this Block by retrieving all the blocks of this page

### Pull Request

I have created a PR to fix this.

**Comment by seratch** [comment]
Fixed by #53
