### ISSUE TITLE
Update block

### ISSUE THREAD

**Issue by Nico-GS** [seratch/notion-sdk-jvm#57]
Hello,

thanks for your SDK.

I can easily create a new page, but I can't modify one.

For create a new page, this code work :
```
return clientNotion.updatePage(
            pageId = PAGE_ID,
            properties = mapOf(
                "Name" to prop(title = listOf(RichText(text = Text(content = "Titre modifié")))),
                "Date" to prop(date = Date(start = "2022-07-05", end = "2022-07-29"))
            )
        )
```

But I can't find the right syntax regarding the modification of my page with the associated block ID :

```
return clientNotion.updateBlock(
            blockId = "6679e3d0ec3341f487eb633c7a59bfa1",
            elements = mapOf(
                "Paragraph" to prop(type = ParagraphBlock)
            )
        )
```

Any idea ?

Thanks :)

**Comment by seratch** [comment]
Hi @Nico-GS, thanks for writing in. I would suggest checking this SDK's integration tests to learn how to use updateBlock method: https://github.com/seratch/notion-sdk-jvm/blob/main/core/src/test/kotlin/integration_tests/BlocksTest.kt

**Comment by Nico-GS** [comment]
Thanks, i did not see that !
