### ISSUE TITLE
Example code in README does not work for me

### ISSUE THREAD

**Issue by brrs** [seratch/notion-sdk-jvm#61]
I was trying to implement code that creates new page like it is in the README guide. I get stuck on this. Notion API says something like:

> body failed validation. Fix one:\nbody.parent.database_id should be defined, instead was `undefined`.\nbody.properties.Title should be not present, instead was `{\"id\":\"199a7d2e-28f4-4d4d-9269-2bb9d739740e\",\"title\":[{...`."}

I thought something wrong with page parent, but it's just "Title" instead of "title" in properties.

I think would be good to update the README file.
```
"Title" to prop(title = listOf(prop.RichText(text = prop.RichText.Text(content = "Fix a bug"))))
```
This and others lines with property types

**Comment by seratch** [comment]
@brrs The example in README works when you prepare a database named "Test Database", with a set of database properties. Sorry for the confusion. Here is a compatible database UI screenshot:

<img width="600" src="https://user-images.githubusercontent.com/19658/178430236-90b14101-8664-4fde-8203-d8a675396b24.png">

The two errors indicate:
* Your database_id in the page parent is null
* Your title property's label is not "Title"

The example set values to variety of properties just for demonstration purpose. You can go with your own properties and property names/IDs.

**Comment by brrs** [comment]
Thank you
