### ISSUE TITLE
Add Comments Support

### ISSUE THREAD

**Issue by eblanchette** [seratch/notion-sdk-jvm#64]
Support for "Comments" would be nice to have. It gives us the ability to record events within a discussion. For example: Emailed the customer a reminder.

**References:**
https://developers.notion.com/reference/comment-object
https://developers.notion.com/reference/retrieve-a-comment
https://developers.notion.com/reference/create-a-comment

**Comment by seratch** [comment]
Yeah, I don't have time for this project right now but I'm planning to add the set of new APIs in future versions

**Comment by eblanchette** [comment]
https://github.com/seratch/notion-sdk-jvm/pull/65

**Comment by seratch** [comment]
Fixed by #65
