### ISSUE TITLE
Configurable HttpClient properties

### ISSUE THREAD

**Issue by ksharma96** [seratch/notion-sdk-jvm#84]
We ran into an issue with an on prem server. It takes > 3 seconds in some situations to connect to the Notion endpoints and the SDK throws a Null Pointer Exception. Have a look at the logs below:

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/67839463/216231309-57c9e1b0-133b-4b6c-a7c2-34a8054aaf77.png">

Can the SDK's NotionClient/NotionHttpClient expose some way to configure the below two properties please @seratch ?

>     private val connectTimeoutMillis: Int = 3_000,
>     private val readTimeoutMillis: Int = 30_000,

These reside inside the `class HttpUrlConnNotionHttpClient` . Would love to have raised a pull request for the same myself, but am just not familiar with Kotlin. 
Cheers.

**Comment by seratch** [comment]
Hi @ksharma96, you can manually instantiate the http client and pass it to NotionClient constructor like it does here: https://github.com/seratch/notion-sdk-jvm/blob/v1.8.0/core/src/main/kotlin/notion/api/v1/NotionClient.kt#L20 

Thanks for asking this! Since I've provided an answer to your question, let me close this issue now.

**Comment by ksharma96** [comment]
Thanks for the prompt response!

**Comment by ksharma96** [comment]
Hey @seratch - the only way exposed in Java to set the client is via setHttpClient method as shown below.

<img width="899" alt="image" src="https://user-images.githubusercontent.com/67839463/216574363-d926ee4e-5565-4ea3-879a-0d44669b147d.png">


Also, the constructor only takes a string as the input for the token in Java. 
<img width="981" alt="image" src="https://user-images.githubusercontent.com/67839463/216575085-4d26a486-2e53-4c6a-9065-042bc8075f0d.png">

**Comment by seratch** [comment]
@ksharma96 Here is an example:

```java
package example;

import notion.api.v1.NotionClient;
import notion.api.v1.http.HttpUrlConnNotionHttpClient;

public class Test {
    public static void main(String[] args) {
        NotionClient client = new NotionClient();
        client.setHttpClient(new HttpUrlConnNotionHttpClient(
                10_000,
                60_000
        ));
    }
}
```
