### ISSUE TITLE
Java UpdatePage fails with JDK 19+

### ISSUE THREAD

**Issue by HearthunterPro** [seratch/notion-sdk-jvm#88]
```
                String id = "49ca77def495470eb6f90ba3702315f8";
		Map<String, PageProperty> pro = new HashMap<>();
		client.updatePage(new UpdatePageRequest(id, pro));
```

after run send this error:

> java.lang.reflect.InaccessibleObjectException: Unable to make field private final sun.net.www.protocol.https.DelegateHttpsURLConnection sun.net.www.protocol.https.HttpsURLConnectionImpl.delegate accessible: module java.base does not "opens sun.net.www.protocol.https" to unnamed module @60e8a46f
> 	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:387)
> 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:363)
> 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:311)
> 	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:180)
> 	at java.base/java.lang.reflect.Field.setAccessible(Field.java:174)
> 	at notion.api.v1.http.HttpUrlConnPatchMethodWorkaround.setPatchRequestMethod$lambda$0(HttpUrlConnPatchMethodWorkaround.kt:45)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
> 	at notion.api.v1.http.HttpUrlConnPatchMethodWorkaround.setPatchRequestMethod(HttpUrlConnPatchMethodWorkaround.kt:36)
> 	at notion.api.v1.http.HttpUrlConnNotionHttpClient.patchTextBody(HttpUrlConnNotionHttpClient.kt:86)
> 	at notion.api.v1.http.NotionHttpClient$DefaultImpls.patchTextBody$default(NotionHttpClient.kt:24)
> 	at notion.api.v1.endpoint.PagesSupport$DefaultImpls.updatePage(PagesSupport.kt:111)
> 	at notion.api.v1.NotionClient.updatePage(NotionClient.kt:12)

I can retrieve page or create page but update Page has error;

i used Eclipse Maven Java JDK 19;

**Comment by seratch** [comment]
Hi @HearthunterPro, thanks for sharing this. I didn't know that the workaround for HttpUrlConnection no longer works with JDK 19+. To resolve this, you can switch to `[java.net.HttpClient](https://docs.oracle.com/en/java/javase/11/docs/api/java.net.http/java/net/http/HttpClient.html)` based one. Check https://github.com/seratch/notion-sdk-jvm#pluggable-http-client to learn how to switch.

**Comment by seratch** [comment]
We may use java.net.HttpClient as the default HTTP client when we drop Java 8 support and out-of-the-box Android runtime support. However, this project won't make the change in the short term. So, when encountering this issue with JDK 19+, please use the optional module along with the core one.
