### ISSUE TITLE
Is there an API wiki for NSJ?

### ISSUE THREAD

**Issue by kamitojaeger** [seratch/notion-sdk-jvm#90]
I'm not familiar with javascript and notion API.
And I couldn't find a wiki that contains info about specific notion API :p

**Comment by seratch** [comment]
What do you mean by NSJ? Either way, https://developers.notion.com/ is the best place to check.

**Comment by kamitojaeger** [comment]
> What do you mean by NSJ? Either way, https://developers.notion.com/ is the best place to check.

I mean I hope there could be a documention or something that lists all the classes and function with example code of how to use them. 

Same with this issue:
https://github.com/seratch/notion-sdk-jvm/issues/78

**Comment by seratch** [comment]
Ah, you meant this SDK by "NSJ" (Notion SDK for JVM, right?) 😮 

I recommend checking the generated javadocs for it: https://oss.sonatype.org/service/local/repositories/releases/archive/com/github/seratch/notion-sdk-jvm-core/1.8.0/notion-sdk-jvm-core-1.8.0-javadoc.jar/!/index.html#package Perhaps, [this URL](https://oss.sonatype.org/service/local/repositories/releases/archive/com/github/seratch/notion-sdk-jvm-core/1.8.0/notion-sdk-jvm-core-1.8.0-javadoc.jar/!/notion/api/v1/endpoint/package-summary.html) may be more relevant. You can find Java methods equivalent to Notion's REST API endpoints.
